# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.5

EAPI=5

MODULE_AUTHOR="ILMARI"
MODULE_VERSION="1.39"


inherit perl-module

DESCRIPTION="Catalyst Development Tools"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="alpha amd64 amd64-fbsd arm arm64 hppa ia64 m68k mips nios2 ppc ppc64 s390 sh sparc sparc-fbsd x86 x86-fbsd   ppc-aix x86-freebsd x64-freebsd sparc64-freebsd hppa-hpux ia64-hpux x86-interix amd64-linux arm-linux ia64-linux ppc64-linux x86-linux ppc-macos x86-macos x64-macos m68k-mint x86-netbsd ppc-openbsd x86-openbsd x64-openbsd sparc-solaris sparc64-solaris x64-solaris x86-solaris x86-winnt x64-cygwin x86-cygwin"
IUSE=""

DEPEND=">=dev-perl/Test-Fatal-0.10.0
	dev-perl/File-Copy-Recursive
	dev-perl/namespace-clean
	perl-gcpan/MooseX-Emulate-Class-Accessor-Fast
	>=perl-gcpan/Catalyst-Plugin-ConfigLoader-0.34
	>=dev-perl/Module-Install-1.60.0
	>=dev-perl/Template-Toolkit-2.240.0
	dev-perl/File-ShareDir
	>=perl-gcpan/Catalyst-Action-RenderView-0.16
	perl-gcpan/MooseX-Daemonize
	>=dev-perl/Path-Class-0.350.0
	dev-perl/namespace-autoclean
	dev-perl/Config-General
	dev-perl/Moose
	>=perl-gcpan/Catalyst-Runtime-5.90097
	>=perl-gcpan/Catalyst-Plugin-Static-Simple-0.33
	perl-gcpan/Starman
	>=perl-gcpan/File-ChangeNotify-0.24
	dev-lang/perl"
