# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.5

EAPI=5

MODULE_AUTHOR="ILMARI"
MODULE_VERSION="0.07043"


inherit perl-module

DESCRIPTION="Create a DBIx::Class::Schema based on a database"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="alpha amd64 amd64-fbsd arm arm64 hppa ia64 m68k mips nios2 ppc ppc64 s390 sh sparc sparc-fbsd x86 x86-fbsd   ppc-aix x86-freebsd x64-freebsd sparc64-freebsd hppa-hpux ia64-hpux x86-interix amd64-linux arm-linux ia64-linux ppc64-linux x86-linux ppc-macos x86-macos x64-macos m68k-mint x86-netbsd ppc-openbsd x86-openbsd x64-openbsd sparc-solaris sparc64-solaris x64-solaris x86-solaris x86-winnt x64-cygwin x86-cygwin"
IUSE=""

DEPEND=">=dev-perl/Class-Unload-0.70.0
	>=dev-perl/Lingua-EN-Tagger-0.25
	>=dev-perl/namespace-clean-0.250.0
	>=dev-perl/DBD-SQLite-1.460.0
	>=dev-perl/Class-Inspector-1.280.0
	dev-perl/DBIx-Class-IntrospectableM2M
	>=dev-perl/Test-Exception-0.320.0
	>=dev-perl/MooseX-NonMoose-0.26
	>=dev-perl/MooseX-MarkAsMethods-0.15
	dev-perl/Try-Tiny
	dev-perl/Class-C3-Componentised
	>=dev-perl/Data-Dump-1.220.0
	dev-perl/DBIx-Class
	>=dev-perl/Hash-Merge-0.120.0
	>=dev-perl/MRO-Compat-0.120.0
	>=dev-perl/String-ToIdentifier-EN-0.11
	dev-perl/Config-Any
	>=dev-perl/namespace-autoclean-0.130.0
	dev-perl/Carp-Clan
	>=dev-perl/String-CamelCase-0.02
	>=dev-perl/Lingua-EN-Inflect-Phrase-0.18
	>=dev-perl/Scalar-List-Utils-1.42
	>=dev-perl/Test-Warn-0.240.0
	>=dev-perl/Test-Deep-0.115.0
	>=dev-perl/Class-Accessor-Grouped-0.100.100
	>=dev-perl/Test-Differences-0.610.0
	>=dev-perl/Scope-Guard-0.200.0
	dev-perl/Config-General
	dev-perl/Moose
	>=dev-perl/Lingua-EN-Inflect-Number-1.12
	>=dev-perl/Test-Pod-1.480.0
	dev-lang/perl"
