# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.5

EAPI=5

MODULE_AUTHOR="JJNAPIORK"
MODULE_VERSION="0.40"


inherit perl-module

DESCRIPTION="Generic Session plugin - ties together server side storage and client side state required to maintain session data."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="alpha amd64 amd64-fbsd arm arm64 hppa ia64 m68k mips nios2 ppc ppc64 s390 sh sparc sparc-fbsd x86 x86-fbsd   ppc-aix x86-freebsd x64-freebsd sparc64-freebsd hppa-hpux ia64-hpux x86-interix amd64-linux arm-linux ia64-linux ppc64-linux x86-linux ppc-macos x86-macos x64-macos m68k-mint x86-netbsd ppc-openbsd x86-openbsd x64-openbsd sparc-solaris sparc64-solaris x64-solaris x86-solaris x86-winnt x64-cygwin x86-cygwin"
IUSE=""

DEPEND="dev-perl/Object-Signature
	dev-perl/Moose
	>=dev-perl/Catalyst-Runtime-5.90097
	dev-perl/Test-WWW-Mechanize-PSGI
	dev-perl/Test-Exception
	dev-perl/Test-Deep
	>=dev-perl/namespace-clean-0.250.0
	>=dev-perl/MooseX-Emulate-Class-Accessor-Fast-0.00903
	dev-perl/MRO-Compat
	dev-lang/perl"
