# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.5

EAPI=5

MODULE_AUTHOR="TEAM"
MODULE_VERSION="0.031"


inherit perl-module

DESCRIPTION="provides client interface to AMQP using L<IO::Async>"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="alpha amd64 amd64-fbsd arm arm64 hppa ia64 m68k mips nios2 ppc ppc64 s390 sh sparc sparc-fbsd x86 x86-fbsd   ppc-aix x86-freebsd x64-freebsd sparc64-freebsd hppa-hpux ia64-hpux x86-interix amd64-linux arm-linux ia64-linux ppc64-linux x86-linux ppc-macos x86-macos x64-macos m68k-mint x86-netbsd ppc-openbsd x86-openbsd x64-openbsd sparc-solaris sparc64-solaris x64-solaris x86-solaris x86-winnt x64-cygwin x86-cygwin"
IUSE=""

DEPEND=">=perl-gcpan/Test-Refcount-0.08
	perl-gcpan/Test-HexString
	>=perl-gcpan/Mixin-Event-Dispatch-1.006
	perl-gcpan/curry
	>=perl-gcpan/Net-AMQP-0.06
	>=dev-perl/File-ShareDir-Install-0.90.0
	perl-gcpan/IO-Async-SSL
	>=perl-gcpan/Variable-Disposition-0.004
	>=dev-perl/Test-CheckDeps-0.10.0
	>=dev-perl/Test-Fatal-0.10.0
	dev-perl/Class-ISA
	>=perl-gcpan/IO-Async-0.68
	dev-perl/List-UtilsBy
	>=perl-gcpan/Future-0.33
	dev-perl/File-ShareDir
	dev-lang/perl"
