# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.5

EAPI=5

MODULE_AUTHOR="GBJK"
MODULE_VERSION="0.65"


inherit perl-module

DESCRIPTION="DBIx::Class::Schema Model Class"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="alpha amd64 amd64-fbsd arm arm64 hppa ia64 m68k mips nios2 ppc ppc64 s390 sh sparc sparc-fbsd x86 x86-fbsd   ppc-aix x86-freebsd x64-freebsd sparc64-freebsd hppa-hpux ia64-hpux x86-interix amd64-linux arm-linux ia64-linux ppc64-linux x86-linux ppc-macos x86-macos x64-macos m68k-mint x86-netbsd ppc-openbsd x86-openbsd x64-openbsd sparc-solaris sparc64-solaris x64-solaris x86-solaris x86-winnt x64-cygwin x86-cygwin"
IUSE=""

DEPEND="dev-perl/MooseX-Types
	dev-perl/Hash-Merge
	>=dev-perl/DBIx-Class-Schema-Loader-0.07043
	dev-perl/Test-Requires
	>=dev-perl/namespace-autoclean-0.130.0
	dev-perl/Carp-Clan
	dev-perl/Tie-IxHash
	>=dev-perl/MooseX-NonMoose-0.26
	dev-perl/Catalyst-Component-InstancePerContext
	dev-perl/Test-Exception
	dev-perl/namespace-clean
	dev-perl/DBD-SQLite
	>=dev-perl/Module-Runtime-0.14.0
	>=dev-perl/CatalystX-Component-Traits-0.19
	>=dev-perl/MooseX-MarkAsMethods-0.15
	dev-perl/Try-Tiny
	dev-perl/List-MoreUtils
	>=dev-perl/Catalyst-Runtime-5.90097
	dev-perl/Moose
	dev-perl/DBIx-Class
	>=dev-perl/MooseX-Types-LoadableClass-0.014
	dev-lang/perl"
